# Generated by Django 4.0.6 on 2022-07-11 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='MountPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_device', to='device.device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='mount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mount_place', to='device.mountplace'),
        ),
    ]
