# Generated by Django 4.0.6 on 2022-07-11 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sport', '0002_alter_activity_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('model_file', models.FileField(upload_to='ml')),
            ],
        ),
        migrations.CreateModel(
            name='TrainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_set', models.JSONField()),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_sport', to='sport.sport')),
            ],
        ),
        migrations.CreateModel(
            name='ModelSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_model', to='mlmodel.mlmodel')),
                ('second_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternate_model', to='mlmodel.mlmodel')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport', to='sport.sport')),
            ],
        ),
    ]
