# Generated by Django 4.0.6 on 2022-07-10 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_alter_activity_sport'),
        ('mlmodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_model', to='mlmodel.mlmodel')),
                ('second_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternate_model', to='mlmodel.mlmodel')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport', to='sport.sport')),
            ],
        ),
    ]
